-- Table Topico
CREATE TABLE IF NOT EXISTS Topic (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    message TEXT NOT NULL,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(50) NOT NULL,
    author INT NOT NULL,
    course INT,
    FOREIGN KEY (author) REFERENCES AppUser(id) ON DELETE CASCADE,
    FOREIGN KEY (course) REFERENCES Course(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;